# Generated by Django 2.0.13 on 2019-04-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studinfo1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('idnumber', models.IntegerField()),
                ('jobstatus', models.CharField(max_length=30)),
                ('passout', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='studinfo',
        ),
    ]
