# Generated by Django 2.2 on 2019-04-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190409_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='studinfo1',
            name='branch',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studinfo1',
            name='jobstatus',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studinfo1',
            name='lastname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studinfo1',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studinfo1',
            name='passout',
            field=models.IntegerField(default=2000),
        ),
    ]
