# Generated by Django 2.2 on 2019-04-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190409_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='studinfo1',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
