# Generated by Django 2.2 on 2019-04-09 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studinfo1_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studinfo1',
            name='mobile',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
